# ----
# Site

title:                  La Bifurcation en tant que processus de singularisation des pratiques artistiques
tagline:                "La Bifurcation en tant que processus de singularisation des pratiques artistiques : Carnet de recherche digressif et interactif en ligne"
url: https://memoire.quaternum.net
baseurl:
google_analytics_key:
show_full_navigation:   true

resume: "Mémoire soutenu à l'EESI de Poitiers-Angoulême sur la question de la Bifurcation comme manière de singulariser des pratiques artistiques - Il sera question de faire un focus spécifiquement sur les pratiques numériques en art (développement, installation, création, ...). "
mots-cles: "édition, livre, chaîne d'édition, chaîne de publication, traitement de texte, logiciel de publication assistée par ordinateur, livre numérique"

abstract: "The book industry, and more specifically the publishing sector, is undergoing profound changes in contact with digital.
After some computerization phases, one of the most visible manifestations of these disruptions is probably the ebook.
If the electronic book is a unique approach to the written word, both in its distribution and its reception, there are deeper transformations in the way books are made.
Publishing organisations imagine new original and unconventional publication chains to generate printed copy as well as multiple digital versions of books and documents, replacing traditional word processors and desktop publishing softwares with methods and technologies from web development.
So a modular publishing system can replace sequential chains, repositioning the human at the core of machines or programs.
Through text commentaries and case analyses we study the book's evolution with a more global view of our relationship to technique, and we expose the founding principles of a new model."
keywords: "publishing, book, publishing chain, word processor, desktop publishin software, ebook"

locale:                 fr_FR

encoding:               UTF-8

date:                   2018
# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo:                   /siteicon.png
description:            "La Bifurcation en tant que processus de singularisation des pratiques artistiques : Carnet de recherche digressif et interactif en ligne. Mémoire d'Etienne Baron sur les pratiques numériques en art"
author:
  name:                 Antoine Fauchié
  email:                antoine@quaternum.net
  twitter:              antoinentl
social:
  name:                 La Bifurcation en tant que processus de singularisation des pratiques artistiques
  links:
    - https://gitlab.com/antoinentl/systeme-modulaire-de-publication/

version: v1.1
versiondate: mardi 26 mars 2019

# -----
# Build

timezone:               Etc/UTC

permalink:              pretty

plugins:
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-microtypo
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - materiaux

collections:
  memoire:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "memoire"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major

# --------------
# Jekyll Scholar
scholar:
  style: apa
  locale: fr
  source: _bibliographie
  bibliography: bibliographie.bib
  relative: "/6-annexes/bibliographie/"
  sort_by: author
  bibliography_list_tag: ul

microtypo:
  median: true

repo_url:             https://gitlab.com/antoinentl/systeme-modulaire-de-publication
repo_branch:          master
