# ----
# Site

title:                  LA BIFURCATION COMME PROCESSUS DE SINGULARISATION DES PRATIQUES ARTISTIQUES
tagline:                "LA BIFURCATION COMME PROCESSUS DE SINGULARISATION DES PRATIQUES ARTISTIQUES Carnet de recherche digressif et interactif en ligne"
url:
baseurl:
google_analytics_key:
show_full_navigation:   true

resume: "Mémoire soutenu à l'EESI de Poitiers-Angoulême sur la question de la Bifurcation comme manière de singulariser des pratiques artistiques - Il sera question de faire un focus spécifiquement sur les pratiques numériques en art (développement, installation, création, ...). "
mots-cles: "bifurcation, numérique, code, programmation, art, nouvelles technologies"

abstract: "Report astonished in EESI Poitiers-Angoulême about Forking and more precisely like meaning of singularisation of craftwerk, especially in digital art (development, instalation,...)"
keywords: "fork, digital art, code, programing, new technologies"

locale:                 fr_FR

encoding:               UTF-8

date:                   2020-2021
# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo:
description:            "LA BIFURCATION COMME PROCESSUS DE SINGULARISATION DES PRATIQUES ARTISTIQUES Carnet de recherche digressif et interactif en ligne"
author:
  name:                 Etienne Baron
  email:                e.baron@eesi.eu
  twitter:
social:
  name:                 Vers un système modulaire de publication
  links:
    -

version: v0.1
versiondate: Samedi 05 Septembre 2020

# -----
# Build

timezone:               Etc/UTC

permalink:              pretty

plugins:
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-microtypo
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - materiaux

collections:
  memoire:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "memoire"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major

# --------------
# Jekyll Scholar
scholar:
  style: apa
  locale: fr
  source: _bibliographie
  bibliography: Bibliographie (2).bib
  relative: "/6-annexes/bibliographie/"
  sort_by: author
  bibliography_list_tag: ul

microtypo:
  median: true

repo_url:
repo_branch:          preview3
